# Generated by Django 4.0.8 on 2022-11-14 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_and_perms', '0006_authorizedapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='identification',
            field=models.CharField(help_text="'%Y-%m-%d %H:%M:%S',   es decir  '2006-10-25 14:30:59'", max_length=15, null=True, validators=[django.core.validators.RegexValidator('"(^[1|5]\\d{11}$)|(^\\d{2}-\\d{4}-\\d{4}$)"', message='Debe tener el formato 08-8888-8888 para nacionales o 500000000000 o 100000000000')]),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='request_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='authenticatedatarequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Solicitud recibida correctamente'), (1, 'Ha ocurrido algún problema al solicitar la firma'), (2, 'Solicitud con campos incompletos'), (3, 'Diferencia de hora no permitida entre cliente y servidor'), (4, 'La entidad no se encuentra registrada'), (5, 'La entidad se encuentra en estado inactiva'), (6, 'La URL no pertenece a la entidad solicitante'), (7, 'El tamaño de hash debe ser entre 1 y 130 caracteres'), (8, 'Algoritmo desconocido'), (9, 'Certificado incorrecto')], default=1),
        ),
    ]
